language: node_js
node_js:
  - "12"
dist: bionic
sudo: required

branches:
  only:
  - master

jobs:
  include:
    - before_script:
        - npm install -g @angular/cli
    - script:
        - npm run build-lib
        - ng lint
        - ng build --prod --base-href /links-buttons/
        - cd dist/links-buttons
        - cp index.html 404.html
        - cd ../..
    - stage: pages
      script: skip
      deploy: &pages
        provider: pages
        skip_cleanup: true
        github-token: $GITHUB_TOKEN
        local_dir: dist/links-buttons
        on:
          branch: master
    - stage: npm
      script: skip
      before_deploy:
        - cd dist/caiocampos/links-buttons
      deploy: &npm
        provider: npm
        skip_cleanup: true
        api_key: $NPM_TOKEN
        email: "caio.campos1204@gmail.com"
        tag: next
        on:
          branch: master