language: node_js
node_js:
  - "12"
dist: bionic
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - npm run build-lib
  - ng lint
  - ng build --prod --base-href /links-buttons/
  - cd dist/links-buttons
  - cp index.html 404.html
  - cd ../..

before_deploy:
  - cd dist/caiocampos/links-buttons

deploy:
  - provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    local_dir: ../../links-buttons
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    api_key: $NPM_TOKEN
    email: "caio.campos1204@gmail.com"
    tag: next
    on:
      branch: master
